#! /bin/sh
# /etc/init.d/starttor
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting tor as daemon."
    sudo tor
    ;;
  stop)
    echo "Stopping tor"
    sudo start-stop-daemon --stop --name tor
    ;;
  *)
    echo "Usage: /etc/init.d/starttor {start|stop}"
    exit 1
    ;;
esac

exit 0

